@StockExchange.WebApi_HostAddress = http://localhost:5053

GET {{StockExchange.WebApi_HostAddress}}/api/company/
Accept: application/json
###
GET {{StockExchange.WebApi_HostAddress}}/api/order/
Accept: application/json
###
GET {{StockExchange.WebApi_HostAddress}}/api/crypto/
Accept: application/json
###